### PR TITLE
Add config for changing meridiem colours

### PR DESCRIPTION
**Pull request by arjunkomath**
Allow config to set both text and background colour for selected meridiem, previously users could only set background color.

Signed-off-by: Arjun Komath <arjunkomath@gmail.com>

### CODE REVIEW

**Comment by arjunkomath** [comment]
@catc Please review this PR.

**Comment by catc** [comment]
I'll look it over tonight.

**Comment by arjunkomath** [comment]
Thanks. Kindly publish to npm if the changes are fine, I'm using this component for a project. 👍

**Comment by catc** [comment]
Merged and published 👍

**Comment by arjunkomath** [comment]
@catc I tried installed the package, the `lib` folder seems to have the old code. Is the `lib` folder generates automatically?

**Comment by catc** [comment]
Forgot to build, can you try again? Should be fixed now.

**Comment by arjunkomath** [comment]
It worked, Thanks. 👍

**Pull request merged**
