### PR TITLE
Add new parameter 'hourMode' to choose between am/pm or 24 hour format

### PR DESCRIPTION
**Pull request by karl-dv**
Resolves issue #4

Default mode remains 12 hour am/pm mode.
However, `<TimeKeeper hourMode={'hour24'} />` results in the following:

image of 24-hour usage

By shifting the outer ring by 1/2 increment, the angle calculated from the click or drag coordinates still uniquely identifies the selected hour. This way, the original implementation didn't need any drastic changes.

I also added some extra tests, and I included a 24 hour example in the docs intro page.

### CODE REVIEW

**Comment by catc** [comment]
Thanks for opening this PR. I'm a bit swamped but should be able to look at it in 2 or so weeks.

**Comment by rossdargan** [comment]
Hi @catc 

Have you had any more thoughts on this p/r?

**Comment by Zanoshky** [comment]
Looks great. @catc  any thoughts?

**Comment by catc** [comment]
Hey, been pretty busy with the move + new job - but hoping to work on it during the next long weekend (in a week and a half).

**Comment by catc** [comment]
I looked through the PR and it looks pretty good. I've started on a major rewrite of the library to v2 including upgrading to react 16.8+ with hooks, typescript, and updating a bunch of outdated libraries (react motion -> react spring). The new version should also include 24 hour mode, and possibly a few other requested features.

**Comment by LoicSellaye** [comment]
Hi and thank you for this useful feature. Could you please tell me how to retrieve your changes and put it in my project? I already done a 'yarn install react-timekeeper' but this feature is not included.

**Comment by catc** [comment]
I haven't yet published the version with 24hr mode - it's still a WIP.

**Comment by LoicSellaye** [comment]
Hi, 
Yes please publish your amazing work as soon as possible. I really need this feature for my project.
Best

**Comment by catc** [comment]
Closed by https://github.com/catc/react-timekeeper/releases/tag/v2.0.0

**Pull request closed without merging**
