### PR TITLE
Fix #47 by preventing click events

### LINKED ISSUE #47: iOS events captured twice
If using an iOS device (tested on safari iOS 13 on iPhone and iPad) a simple tap to choose an hour will also select the minute with the closest placement.

This behavior is not so bad if the picker does not close itself, but I built one with the option `closeOnMinuteSelect` enabled and what happens is that with one tap both get selected and the picker closes. Thus the only choosable times are 12:00, 1:05, 6:30, etc...

This does not happen if instead of tapping the finger is held, dragged around and released.

I inspected the events firing in mobile safari and it seems like there are both touch and click events going on. My guess is that there is a `preventdefault` call missing in the touchstart or touchdown events, that would tell iOS not to generate a click one as well, but I'm not sure. I haven't tested it deeply.

Here is a screencast showing the problem. I'm only clicking on the hours and you can see the seconds immediately change (then I click on the hour number at the top to try again).

ezgif-7-d15e82cd09f8

### PR DESCRIPTION
**Pull request by erpheus**
Closes #47 

Attached touchstart event to clock to allow cancelation and thus prevent click event triggering.

### CODE REVIEW

**Comment by erpheus** [comment]
Just wanted to leave the process and the reasoning behind the solution documented here:

As can be seen in the related issue #47, mobile safari was triggering click events after the touch events had already fired. This is common in mobile browsers to allow websites to just implement click handlers if they don't need anything specific to touch events. As the clock allows dragging the finger around the clock, this is not the case.

A solution was already in place which consisted on a react state that would prevent click handlers from doing anything for 10 milliseconds after a touch event was detected. Increasing those 10 milliseconds to a 100 already seemed sufficient to make the solution also work on my devices, but it didn't feel like the best solution.

Usually it is enough with just calling e.preventDefault() on the touchstart event, which signals the browser that the touch will be handled and there is no need for click events. But it didn't work here since the events that were being delivered to the onTouchStart handler were not cancelable. Apparently this happens when the event listener is not set to the element itself but to the document, and it turns out that is exatly [what react does with its *onEvent* props](https://github.com/facebook/react/issues/9809) ([for now](https://github.com/facebook/react/issues/2043)).

As suggested in the first link, the only option for now is to use the addEventListener function manually. I did it using an approach similar to the one mentioned in [this post](https://dev.to/adrianbdesigns/custom-react-hooks-useeventlistener-1kp). At first I tried to go for having both the mousedown and touchstart events in the same way but that made the testing super complex since enzyme's `simulate` method relies on the *onEvent* way of adding listeners in react, and it seems quite quite complex to change it to use the handlers added by addEventListener (I tried for a while). So that also explains why I didn't add any more tests, as this is also quite a browser-specific behavior to properly simulate in the tests.

**Comment by erpheus** [comment]
ping @catc ;)

Let me know if you want any help / screen recordings for testing this.

**Comment by catc** [comment]
Hey @erpheus I'm going to try to dedicate some time to this closer to Christmas when I have more time. I did briefly look at it and I think it changed some of the original user interaction - I need investigate further. I'll definitely ping you if I need some help testing on ios.

**Comment by erpheus** [comment]
That sounds great! I have no rush but didn’t want it to get forgotten either :)

**Comment by jBenes** [comment]
Hi, @catc, are you still going to work on this issue? I can help with iOS. Thanks

**Comment by jBenes** [comment]
Btw what about adding optional parameter which would set disableMouse timeout or as mentioned above, raise it to 100 or 150ms? Even though it's not the best solution, it should work 99% times and it's still better than nothing :)

**Comment by catc** [comment]
Will take a look at this in dec when I have some more time.

**Comment by catc** [comment]
Released fix as v2.2.1 - thanks for driving this @erpheus!

**Pull request closed without merging**
